# Generated by Django 3.1.2 on 2021-06-09 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210525_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_test', models.CharField(max_length=50)),
                ('hospital_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'MedicalTest',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
        migrations.CreateModel(
            name='MedicalTestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('report_date', models.DateField()),
                ('range_of_test', models.CharField(max_length=50, null=True)),
                ('result', models.DecimalField(decimal_places=4, max_digits=6)),
                ('unit', models.CharField(max_length=10)),
                ('medical_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicaltest')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'MedicalTestRecord',
            },
        ),
    ]
