# Generated by Django 3.1.2 on 2021-06-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210610_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltestrecord',
            name='medical_test_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
