# Generated by Django 3.1.2 on 2021-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210610_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltestrecord',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
